DROP TABLE IF EXISTS BILL_CACHE_H2;

CREATE TABLE BILL_CACHE_H2
(
    id BIGINT(20) NOT NULL AUTO_INCREMENT  COMMENT '主键ID' ,
    bill_no VARCHAR(30) NULL DEFAULT NULL COMMENT '单号',
    transfer_state INT(11) NULL DEFAULT NULL COMMENT '单据传输状态',
    message VARCHAR(30) NULL DEFAULT NULL COMMENT '单据传输信息',
    error_code VARCHAR(30) NULL DEFAULT NULL COMMENT '错误码',
    create_date Datetime NULL DEFAULT NULL COMMENT '创建日期',
    retries INT(11) NULL DEFAULT NULL COMMENT '传输重试次数',
    PRIMARY KEY (id)
);
